package model;

public enum Companias {
    VUELING,
    RYANAIR,
    EMIRATES,
    AMERICAN_AIRLINES,
    AIR_FRANCE,
    IBERIA,
    QATAR_AIRWAYS,
    EASYJET,
    BRITISH_AIRWAYS, ALITALIA, AIREUROPA
}
